### ISSUE TITLE
Les 1-3

### ISSUE THREAD

**Issue by Supernova288** [Supernova288/Front#1]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Document</title>
</head>
<body>
    <div style="color: blue;" class="top">
        <h1>  Я верх</h1>
        <div >
            Я внутри дркого блока <span>Я строка внутри блока</span>
  <label>Личные данные:
    <input type="text" placeholder="Логин" name="q">
    <input type="text" placeholder="Пароль" name="q">
  </label>    
  <button type="submit">Ввод</button>
</form> 
        </div>
    </div>
    <div class="bottom">  Я низ</div>
    <img src="https://avatars.mds.yandex.net/i?id=7a436e4c549b35832230bac155d65a28_l-7575569-images-thumbs&n=13">
</body>
</html>

**Comment by vitaliik84** [comment]
Good
